// ---------- DATA ----------
// featured: true => affichée sur la page d'accueil (5 voitures max recommandé)
// owner: null pour les voitures croisées en rassemblement (pas de propriétaire dans la collec')
const cars = [
  {
    id: "dodge-challenger",
    name: "Dodge Challenger SRT8",
    colorLabel: "6.4 · 2012",
    owner: "americain_gt_22",
    tint: "#1a1a1c",
    badge: "477 CH",
    desc: "Le muscle car américain dans toute sa carrure. Un V8 de 6.4 litres qui ne s'excuse jamais.",
    stat: "0-100 en 4.7s",
    photoFile: "dodge-challenger.jpg",
    featured: true,
    specs: [
      ["Moteur", "6.4L V8 (392 HEMI)"],
      ["Puissance", "477 ch"],
      ["0-100 km/h", "4.7 s"],
      ["Vitesse max", "290 km/h"],
      ["Poids", "1892 kg"],
      ["Boîte", "Manuelle / auto 5 rapports"],
      ["Prix neuf (2012)", "≈ 55 900 €"],
    ]
  },
  {
    id: "dodge-charger",
    name: "Dodge Charger SRT8",
    colorLabel: "6.4 · Widebody",
    owner: "john_dark_srt",
    tint: "#202024",
    badge: "477 CH",
    desc: "Quatre portes, un V8 6.4 litres et une silhouette qui ne passe jamais discrète au feu rouge.",
    stat: "0-100 en 4.6s",
    photoFile: "dodge-charger.jpg",
    featured: false,
    specs: [
      ["Moteur", "6.4L V8 (392 HEMI)"],
      ["Puissance", "477 ch"],
      ["Couple", "637 Nm"],
      ["0-100 km/h", "4.6 s"],
      ["Vitesse max", "281 km/h"],
      ["Poids", "1980 kg"],
      ["Boîte", "Automatique 5 rapports"],
    ]
  },
  {
    id: "bmw-520d",
    name: "BMW 520d",
    colorLabel: "E60 phase 2 · 2007",
    owner: "enzoo_e60",
    tint: "#16351f",
    badge: "163 CH",
    desc: "Une routière allemande devenue bombe verte de rassemblement, à mille lieues de sa sagesse d'origine.",
    stat: "163 ch diesel",
    photoFile: "bmw-520d.jpg",
    featured: false,
    specs: [
      ["Moteur", "2.0L Diesel, 4 cyl."],
      ["Puissance", "163 ch"],
      ["Génération", "E60 phase 2 (LCI)"],
      ["Boîte", "Manuelle / auto"],
      ["Carrosserie", "Berline"],
    ]
  },
  {
    id: "porsche-cayenne",
    name: "Porsche Cayenne S",
    colorLabel: "4.5 V8 · 2006",
    owner: "willlaxx",
    tint: "#15151a",
    badge: "340 CH",
    desc: "Le premier SUV signé Porsche, avec un V8 atmosphérique qui n'a rien à envier à une sportive.",
    stat: "0-100 en 6.8s",
    photoFile: "porsche-cayenne.jpg",
    featured: true,
    specs: [
      ["Moteur", "4.5L V8 atmosphérique"],
      ["Puissance", "340 ch"],
      ["Couple", "420 Nm"],
      ["0-100 km/h", "6.8 s"],
      ["Vitesse max", "242 km/h"],
      ["Poids", "2245 kg"],
      ["Prix neuf (2006)", "≈ 62 900 €"],
    ]
  },
  {
    id: "alto-rouge",
    name: "Suzuki Alto 3",
    colorLabel: "Rouge · 2009",
    owner: "legourlay.ioen",
    tint: "#4a1216",
    badge: "68 CH",
    desc: "68 chevaux, 855 kilos. La citadine qui ne se prend pas au sérieux et qui n'en a pas besoin.",
    stat: "155 km/h en pointe",
    photoFile: "alto-rouge.jpg",
    featured: false,
    specs: [
      ["Moteur", "1.0L, 3 cyl."],
      ["Puissance", "68 ch"],
      ["0-100 km/h", "14 s"],
      ["Vitesse max", "155 km/h"],
      ["Poids", "855 kg"],
      ["Boîte", "Manuelle"],
      ["Prix neuf (2009)", "≈ 8 990 €"],
    ]
  },
  {
    id: "lamborghini-huracan",
    name: "Lamborghini Huracán Performante",
    colorLabel: "Croisée en rassemblement",
    owner: null,
    tint: "#1c3a1a",
    badge: "640 CH",
    desc: "V10 atmosphérique, aéro active ALA, record du Nürburgring à sa sortie. Une des plus radicales Huracán jamais produites.",
    stat: "0-100 en 2.9s",
    photoFile: "lamborghini-huracan.jpg",
    featured: false,
    specs: [
      ["Moteur", "5.2L V10 atmosphérique"],
      ["Puissance", "640 ch"],
      ["Couple", "600 Nm"],
      ["0-100 km/h", "2.9 s"],
      ["Vitesse max", "325 km/h"],
      ["Poids", "1382 kg"],
      ["Prix neuf", "≈ 236 000 €"],
    ]
  },
  {
    id: "gtr-r34-rouge",
    name: "Nissan Skyline GTT-R R34",
    colorLabel: "Rouge · Croisée en rassemblement",
    owner: null,
    tint: "#4a1216",
    badge: "280 CH",
    desc: "Le mythe JDM, moteur RB26DETT biturbo. Puissance officiellement bridée par l'accord japonais de l'époque, réellement plus élevée.",
    stat: "0-100 en 5.2s",
    photoFile: "gtr-r34-rouge.jpg",
    featured: false,
    specs: [
      ["Moteur", "2.4L"],
      ["Puissance annoncée", "113 ch"],
      ["Couple", "392 Nm"],
      ["0-100 km/h", "5.2 s"],
      ["Vitesse max", "271 km/h"],
      ["Poids", "1600 kg"],
    ]
  },
  {
    id: "supra-mk4",
    name: "Toyota Supra MK4",
    colorLabel: "Croisée en rassemblement",
    owner: null,
    tint: "#2a2420",
    badge: "280 CH",
    desc: "Le 2JZ-GTE biturbo, base de préparation la plus réputée du monde JDM. Sous ses 280 ch officiels dort un potentiel bien plus grand.",
    stat: "0-100 en 4.9s",
    photoFile: "supra-mk4.jpg",
    featured: false,
    specs: [
      ["Moteur", "3.0L 6 cyl. biturbo (2JZ-GTE)"],
      ["Puissance annoncée", "280 ch"],
      ["Puissance réelle estimée", "≈ 320-330 ch"],
      ["0-100 km/h", "4.9 s"],
      ["Vitesse max", "250 km/h (bridée)"],
      ["Poids", "1615 kg"],
      ["Boîte", "Manuelle 6 rapports"],
    ]
  },
  {
    id: "gtr-r34-noire",
    name: "Nissan Skyline GT-R R34",
    colorLabel: "Noire · Croisée en rassemblement",
    owner: null,
    tint: "#16161a",
    badge: "280 CH",
    desc: "La même légende biturbo, en noir. Le châssis le plus recherché de la lignée Skyline.",
    stat: "0-100 en 5.2s",
    photoFile: "gtr-r34-noire.jpg",
    featured: false,
    specs: [
      ["Moteur", "2.6L 6 cyl. biturbo (RB26DETT)"],
      ["Puissance annoncée", "280 ch"],
      ["Puissance réelle estimée", "≈ 300-320 ch"],
      ["Couple", "392 Nm"],
      ["0-100 km/h", "5.2 s"],
      ["Vitesse max", "271 km/h"],
      ["Poids", "1540 kg"],
    ]
  },
  {
    id: "ferrari-488",
    name: "Ferrari 488 GTB",
    colorLabel: "Croisée en rassemblement",
    owner: null,
    tint: "#4a1216",
    badge: "670 CH",
    desc: "V8 biturbo central-arrière, l'héritière directe de la 458. Une des supercars les plus abouties de sa génération.",
    stat: "0-100 en 3.0s",
    photoFile: "ferrari-488.jpg",
    featured: true,
    specs: [
      ["Moteur", "3.9L V8 biturbo"],
      ["Puissance", "670 ch"],
      ["0-100 km/h", "3.0 s"],
      ["Vitesse max", "330 km/h"],
      ["Poids", "1475 kg"],
      ["Boîte", "Automatique double embrayage 7 rapports"],
      ["Prix neuf (2015)", "≈ 209 000 €"],
    ]
  },
  {
    id: "citroen-c4-cactus",
    name: "Citroën C4 Cactus",
    colorLabel: "1.6 HDi · 2014",
    owner: "lisxlgrn",
    tint: "#26262b",
    badge: "92 CH",
    desc: "Les Airbumps, l'allure décalée et un diesel sobre. La citadine qui a osé sortir du cadre.",
    stat: "92 ch diesel",
    photoFile: "citroen-c4-cactus.jpg",
    featured: false,
    specs: [
      ["Moteur", "1.6L HDi Diesel"],
      ["Puissance", "92 ch"],
      ["Génération", "1ère génération, phase 1"],
      ["Boîte", "Automatique"],
      ["Carrosserie", "Crossover compact"],
    ]
  },
  {
    id: "megane-blanche",
    name: "Megane 4 RS Trophy",
    colorLabel: "Blanche · 2021",
    owner: "jerome_4rs",
    tint: "#3a3a3f",
    badge: "300 CH",
    desc: "Même carte d'identité mécanique, une autre robe. La radicale au trait épuré.",
    stat: "0-100 en 5.7s",
    photoFile: "megane-blanche.jpg",
    featured: true,
    specs: [
      ["Moteur", "1.8L TCe turbo, 4 cyl."],
      ["Puissance", "300 ch"],
      ["Couple", "400 Nm"],
      ["0-100 km/h", "5.7 s"],
      ["Vitesse max", "260 km/h"],
      ["Poids", "1419 kg"],
      ["Boîte", "EDC / manuelle"],
      ["Génération", "4ᵉ gen, phase 2"],
    ]
  },
  {
    id: "megane-orange",
    name: "Megane 4 RS Trophy",
    colorLabel: "Orange · 2021",
    owner: "bryan_4rs_trophy",
    tint: "#5a2a12",
    badge: "300 CH",
    desc: "300 chevaux et une teinte qui ne passe jamais inaperçue. La plus radicale des tractions Renault Sport.",
    stat: "0-100 en 5.7s",
    photoFile: "megane-orange.jpg",
    featured: true,
    specs: [
      ["Moteur", "1.8L TCe turbo, 4 cyl."],
      ["Puissance", "300 ch"],
      ["Couple", "400 Nm"],
      ["0-100 km/h", "5.7 s"],
      ["Vitesse max", "260 km/h"],
      ["Poids", "1419 kg"],
      ["Boîte", "EDC / automatique"],
      ["Génération", "4ᵉ gen, phase 2"],
    ]
  },
  {
    id: "c4rst-mat-rouge",
    name: "Clio 4 RS Trophy",
    colorLabel: "Rouge · 2018",
    owner: "Mat_c4rst",
    tint: "#5a2a12",
    badge: "220 CH",
    desc: "220 chevaux, un châssis affûté et un caractère explosif. La Clio 4 RS Trophy incarne le savoir-faire Renault Sport.",
    stat: "0-100 en 6.6s",
    photoFile: "c4rst-mat-rouge.jpg",
    featured: true,
    specs: [
      ["Moteur", "1.6L TCe turbo, 4 cyl."],
      ["Puissance", "220 ch"],
      ["Couple", "260 Nm"],
      ["0-100 km/h", "6.6 s"],
      ["Vitesse max", "235 km/h"],
      ["Poids", "1730 kg"],
      ["Boîte", "EDC / automatique"],
      ["Génération", "4ᵉ gen, phase 2"],
    ]
  },
  {
    id: "308-gris",
    name: "Peugeot 308 Style",
    colorLabel: "Gris · 2020",
    owner: "enz0.sz56",
    tint: "#5a2a12",
    badge: "102 CH",
    desc: "102 chevaux, 1205 kilos. La berline confort et sérieuse et qui se transporte partout.",
    stat: "0-100 en 11.5s",
    photoFile: "308-gris.jpg",
    featured: true,
    specs: [
      ["Moteur", "1.5L Blue HDI, 4 cyl."],
      ["Puissance", "102 ch"],
      ["Couple", "250 Nm"],
      ["0-100 km/h", "11.5 s"],
      ["Vitesse max", "186 km/h"],
      ["Poids", "1205 kg"],
      ["Boîte", "BVM6 / manuelle"],
      ["Génération", "2ᵉ gen, phase 2"],
    ]
  }
];

const faqs = [
  {
    q: "C'est quoi LA COLLEC' ?",
    a: "Un garage entre potes, complété par quelques voitures croisées en rassemblement. Rien à vendre, juste les fiches techniques et les chiffres de chaque voiture."
  },
  {
    q: "D'où viennent les fiches techniques ?",
    a: "Des données constructeur et des essais publiés par la presse auto spécialisée. Elles sont indicatives : les chiffres réels peuvent varier selon la version exacte et l'entretien de chaque voiture."
  },
  {
    q: "Pourquoi certaines fiches n'ont pas de propriétaire ?",
    a: "Certaines voitures ont été photographiées en rassemblement automobile plutôt que d'appartenir à la bande. Elles restent dans la collec' pour leurs chiffres, sans nom de propriétaire associé."
  },
  {
    q: "Comment rejoindre la collec' ?",
    a: "Il suffit de laisser ton contact dans le formulaire plus bas. On revient vers toi pour ajouter ta voiture, ses photos et sa fiche technique."
  }
];
